<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220155658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contenu_enrichi (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT DEFAULT NULL, url_acces VARCHAR(255) DEFAULT NULL, ordre_affichage INT DEFAULT NULL, date_ajout DATETIME DEFAULT NULL, id_oeuvre_id INT NOT NULL, id_employe_id INT DEFAULT NULL, INDEX IDX_A88859EA82CF1CF (id_oeuvre_id), INDEX IDX_A88859EAA43CD245 (id_employe_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE traduction_artiste (id INT AUTO_INCREMENT NOT NULL, traduction_texte LONGTEXT DEFAULT NULL, url_acces VARCHAR(500) DEFAULT NULL, date_ajout DATETIME DEFAULT NULL, id_artiste_id INT NOT NULL, id_langue_id INT NOT NULL, id_employe_id INT DEFAULT NULL, INDEX IDX_A238993F8458D893 (id_artiste_id), INDEX IDX_A238993FAA9806EA (id_langue_id), INDEX IDX_A238993FA43CD245 (id_employe_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE traduction_contenue_enrichie (id INT AUTO_INCREMENT NOT NULL, traduction_texte LONGTEXT DEFAULT NULL, url_acces VARCHAR(500) DEFAULT NULL, date_ajout DATETIME DEFAULT NULL, ordre_affichage INT DEFAULT NULL, id_contenu_enrichi_id INT NOT NULL, id_langue_id INT NOT NULL, id_employe_id INT DEFAULT NULL, INDEX IDX_E2C8D358C90CCF4E (id_contenu_enrichi_id), INDEX IDX_E2C8D358AA9806EA (id_langue_id), INDEX IDX_E2C8D358A43CD245 (id_employe_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE traduction_expo (id INT AUTO_INCREMENT NOT NULL, traduction_texte LONGTEXT DEFAULT NULL, url_acces VARCHAR(500) DEFAULT NULL, date_ajout DATETIME DEFAULT NULL, id_exposition_id INT NOT NULL, id_langue_id INT NOT NULL, id_employe_id INT DEFAULT NULL, INDEX IDX_2EE6C63D36C5960A (id_exposition_id), INDEX IDX_2EE6C63DAA9806EA (id_langue_id), INDEX IDX_2EE6C63DA43CD245 (id_employe_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE contenu_enrichi ADD CONSTRAINT FK_A88859EA82CF1CF FOREIGN KEY (id_oeuvre_id) REFERENCES oeuvre (id)');
        $this->addSql('ALTER TABLE contenu_enrichi ADD CONSTRAINT FK_A88859EAA43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE traduction_artiste ADD CONSTRAINT FK_A238993F8458D893 FOREIGN KEY (id_artiste_id) REFERENCES artiste (id)');
        $this->addSql('ALTER TABLE traduction_artiste ADD CONSTRAINT FK_A238993FAA9806EA FOREIGN KEY (id_langue_id) REFERENCES langue (id)');
        $this->addSql('ALTER TABLE traduction_artiste ADD CONSTRAINT FK_A238993FA43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE traduction_contenue_enrichie ADD CONSTRAINT FK_E2C8D358C90CCF4E FOREIGN KEY (id_contenu_enrichi_id) REFERENCES contenu_enrichi (id)');
        $this->addSql('ALTER TABLE traduction_contenue_enrichie ADD CONSTRAINT FK_E2C8D358AA9806EA FOREIGN KEY (id_langue_id) REFERENCES langue (id)');
        $this->addSql('ALTER TABLE traduction_contenue_enrichie ADD CONSTRAINT FK_E2C8D358A43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE traduction_expo ADD CONSTRAINT FK_2EE6C63D36C5960A FOREIGN KEY (id_exposition_id) REFERENCES exposition (id)');
        $this->addSql('ALTER TABLE traduction_expo ADD CONSTRAINT FK_2EE6C63DAA9806EA FOREIGN KEY (id_langue_id) REFERENCES langue (id)');
        $this->addSql('ALTER TABLE traduction_expo ADD CONSTRAINT FK_2EE6C63DA43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE contenuenrichi DROP FOREIGN KEY `contenuenrichi_ibfk_1`');
        $this->addSql('ALTER TABLE contenuenrichi DROP FOREIGN KEY `contenuenrichi_ibfk_2`');
        $this->addSql('ALTER TABLE traductionartiste DROP FOREIGN KEY `traductionartiste_ibfk_1`');
        $this->addSql('ALTER TABLE traductionartiste DROP FOREIGN KEY `traductionartiste_ibfk_2`');
        $this->addSql('ALTER TABLE traductionartiste DROP FOREIGN KEY `traductionartiste_ibfk_3`');
        $this->addSql('ALTER TABLE traductioncontenuenrichi DROP FOREIGN KEY `traductioncontenuenrichi_ibfk_1`');
        $this->addSql('ALTER TABLE traductioncontenuenrichi DROP FOREIGN KEY `traductioncontenuenrichi_ibfk_2`');
        $this->addSql('ALTER TABLE traductioncontenuenrichi DROP FOREIGN KEY `traductioncontenuenrichi_ibfk_3`');
        $this->addSql('ALTER TABLE traductionexpo DROP FOREIGN KEY `traductionexpo_ibfk_1`');
        $this->addSql('ALTER TABLE traductionexpo DROP FOREIGN KEY `traductionexpo_ibfk_2`');
        $this->addSql('ALTER TABLE traductionexpo DROP FOREIGN KEY `traductionexpo_ibfk_3`');
        $this->addSql('DROP TABLE contenuenrichi');
        $this->addSql('DROP TABLE traductionartiste');
        $this->addSql('DROP TABLE traductioncontenuenrichi');
        $this->addSql('DROP TABLE traductionexpo');
        $this->addSql('ALTER TABLE artiste DROP FOREIGN KEY `artiste_ibfk_1`');
        $this->addSql('DROP INDEX idEmploye ON artiste');
        $this->addSql('ALTER TABLE artiste MODIFY idArtiste INT NOT NULL');
        $this->addSql('ALTER TABLE artiste ADD annee_naissance INT DEFAULT NULL, ADD date_ajout DATETIME DEFAULT NULL, ADD id_employe_id INT DEFAULT NULL, DROP anneeNaissance, DROP dateAjout, DROP idEmploye, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE idArtiste id INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE artiste ADD CONSTRAINT FK_9C07354FA43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('CREATE INDEX IDX_9C07354FA43CD245 ON artiste (id_employe_id)');
        $this->addSql('DROP INDEX cle ON configuration');
        $this->addSql('ALTER TABLE configuration MODIFY idConfiguration INT NOT NULL');
        $this->addSql('ALTER TABLE configuration CHANGE valeur valeur LONGTEXT DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE idConfiguration id INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY `consultation_ibfk_1`');
        $this->addSql('DROP INDEX idxConsultationDate ON consultation');
        $this->addSql('DROP INDEX idxConsultationOeuvre ON consultation');
        $this->addSql('ALTER TABLE consultation MODIFY idConsultation INT NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD date_consultation DATETIME DEFAULT NULL, DROP dateConsultation, CHANGE idConsultation id INT AUTO_INCREMENT NOT NULL, CHANGE idOeuvre id_oeuvre_id INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A682CF1CF FOREIGN KEY (id_oeuvre_id) REFERENCES oeuvre (id)');
        $this->addSql('CREATE INDEX IDX_964685A682CF1CF ON consultation (id_oeuvre_id)');
        $this->addSql('ALTER TABLE emplacement DROP FOREIGN KEY `emplacement_ibfk_1`');
        $this->addSql('ALTER TABLE emplacement DROP FOREIGN KEY `emplacement_ibfk_2`');
        $this->addSql('DROP INDEX idxEmplacementEspace ON emplacement');
        $this->addSql('DROP INDEX idxEmplacementExpo ON emplacement');
        $this->addSql('ALTER TABLE emplacement MODIFY idEmplacement INT NOT NULL');
        $this->addSql('ALTER TABLE emplacement ADD position_x NUMERIC(5, 2) DEFAULT NULL, ADD position_y NUMERIC(5, 2) DEFAULT NULL, ADD id_espace_id INT NOT NULL, ADD id_exposition_id INT NOT NULL, DROP positionX, DROP positionY, DROP idEspace, DROP idExposition, CHANGE idEmplacement id INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE emplacement ADD CONSTRAINT FK_C0CF65F636BDE04B FOREIGN KEY (id_espace_id) REFERENCES espace (id)');
        $this->addSql('ALTER TABLE emplacement ADD CONSTRAINT FK_C0CF65F636C5960A FOREIGN KEY (id_exposition_id) REFERENCES exposition (id)');
        $this->addSql('CREATE INDEX IDX_C0CF65F636BDE04B ON emplacement (id_espace_id)');
        $this->addSql('CREATE INDEX IDX_C0CF65F636C5960A ON emplacement (id_exposition_id)');
        $this->addSql('ALTER TABLE employe DROP FOREIGN KEY `employe_ibfk_1`');
        $this->addSql('DROP INDEX email ON employe');
        $this->addSql('DROP INDEX idFonction ON employe');
        $this->addSql('DROP INDEX idxEmployeActif ON employe');
        $this->addSql('DROP INDEX idxEmployeSupprime ON employe');
        $this->addSql('DROP INDEX login ON employe');
        $this->addSql('ALTER TABLE employe MODIFY idEmploye INT NOT NULL');
        $this->addSql('ALTER TABLE employe ADD date_suppression DATETIME DEFAULT NULL, ADD id_fonction_id INT NOT NULL, DROP dateCreation, DROP idFonction, CHANGE actif actif SMALLINT DEFAULT NULL, CHANGE supprime supprime SMALLINT DEFAULT NULL, CHANGE idEmploye id INT AUTO_INCREMENT NOT NULL, CHANGE dateSuppression date_creation DATETIME DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE employe ADD CONSTRAINT FK_F804D3B94F9A54D7 FOREIGN KEY (id_fonction_id) REFERENCES fonction (id)');
        $this->addSql('CREATE INDEX IDX_F804D3B94F9A54D7 ON employe (id_fonction_id)');
        $this->addSql('DROP INDEX nomEspace ON espace');
        $this->addSql('ALTER TABLE espace MODIFY idEspace INT NOT NULL');
        $this->addSql('ALTER TABLE espace CHANGE description description LONGTEXT DEFAULT NULL, CHANGE idEspace id INT AUTO_INCREMENT NOT NULL, CHANGE nomEspace nom_espace VARCHAR(250) NOT NULL, CHANGE superficieM2 superficie_m2 NUMERIC(10, 2) DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE etape DROP FOREIGN KEY `etape_ibfk_1`');
        $this->addSql('DROP INDEX idExposition ON etape');
        $this->addSql('DROP INDEX IDX_285F75DD3EC5E3F9 ON etape');
        $this->addSql('ALTER TABLE etape MODIFY idEtape INT NOT NULL');
        $this->addSql('ALTER TABLE etape CHANGE idEtape id INT AUTO_INCREMENT NOT NULL, CHANGE idExposition id_exposition_id INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE etape ADD CONSTRAINT FK_285F75DD36C5960A FOREIGN KEY (id_exposition_id) REFERENCES exposition (id)');
        $this->addSql('CREATE INDEX IDX_285F75DD36C5960A ON etape (id_exposition_id)');
        $this->addSql('ALTER TABLE exposition DROP FOREIGN KEY `exposition_ibfk_1`');
        $this->addSql('DROP INDEX idEmploye ON exposition');
        $this->addSql('DROP INDEX idxExpositionActif ON exposition');
        $this->addSql('DROP INDEX idxExpositionDates ON exposition');
        $this->addSql('ALTER TABLE exposition MODIFY idExposition INT NOT NULL');
        $this->addSql('ALTER TABLE exposition ADD date_debut DATE DEFAULT NULL, ADD date_fin DATE DEFAULT NULL, ADD module_public_actif SMALLINT DEFAULT NULL, ADD date_creation DATETIME DEFAULT NULL, DROP dateDebut, DROP dateFin, DROP modulePublicActif, DROP dateCreation, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE theme theme VARCHAR(255) DEFAULT NULL, CHANGE horaires horaires LONGTEXT DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE image image VARCHAR(255) DEFAULT NULL, CHANGE idExposition id INT AUTO_INCREMENT NOT NULL, CHANGE idEmploye id_employe_id INT DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE exposition ADD CONSTRAINT FK_BC31FD13A43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('CREATE INDEX IDX_BC31FD13A43CD245 ON exposition (id_employe_id)');
        $this->addSql('DROP INDEX intitule ON fonction');
        $this->addSql('ALTER TABLE fonction ADD id INT AUTO_INCREMENT NOT NULL, DROP idFonction, CHANGE intitule intitule VARCHAR(255) NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX code ON langue');
        $this->addSql('ALTER TABLE langue MODIFY idLangue INT NOT NULL');
        $this->addSql('ALTER TABLE langue CHANGE idLangue id INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY `oeuvre_ibfk_1`');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY `oeuvre_ibfk_2`');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY `oeuvre_ibfk_3`');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY `oeuvre_ibfk_4`');
        $this->addSql('DROP INDEX idEmplacement ON oeuvre');
        $this->addSql('DROP INDEX idEmploye ON oeuvre');
        $this->addSql('DROP INDEX idxOeuvreArtiste ON oeuvre');
        $this->addSql('DROP INDEX idxOeuvreExposition ON oeuvre');
        $this->addSql('DROP INDEX idxOeuvreTechnique ON oeuvre');
        $this->addSql('DROP INDEX numeroIdentification ON oeuvre');
        $this->addSql('ALTER TABLE oeuvre MODIFY idOeuvre INT NOT NULL');
        $this->addSql('ALTER TABLE oeuvre ADD annee_creation INT DEFAULT NULL, ADD hauteur_cm NUMERIC(10, 2) DEFAULT NULL, ADD largeur_cm NUMERIC(10, 2) DEFAULT NULL, ADD profondeur_cm NUMERIC(10, 2) DEFAULT NULL, ADD date_livraison_prevue DATE DEFAULT NULL, ADD date_livraison_reelle DATE DEFAULT NULL, ADD ordre_visite INT DEFAULT NULL, ADD url_qr_code VARCHAR(500) NOT NULL, ADD datetime VARCHAR(255) NOT NULL, ADD date_ajout DATETIME DEFAULT NULL, ADD numero_identification INT DEFAULT NULL, ADD id_exposition_id INT DEFAULT NULL, ADD id_emplacement_id INT DEFAULT NULL, ADD id_employe_id INT DEFAULT NULL, DROP anneeCreation, DROP hauteurCm, DROP largeurCm, DROP profondeurCm, DROP dateLivraisonPrevue, DROP dateLivraisonReelle, DROP numeroIdentification, DROP ordreVisite, DROP urlQrCode, DROP dateAjout, DROP idExposition, DROP idEmplacement, DROP idEmploye, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE image image VARCHAR(500) DEFAULT NULL, CHANGE technique technique VARCHAR(255) NOT NULL, CHANGE idOeuvre id INT AUTO_INCREMENT NOT NULL, CHANGE idArtiste id_artiste_id INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT FK_35FE2EFE36C5960A FOREIGN KEY (id_exposition_id) REFERENCES exposition (id)');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT FK_35FE2EFEF93F3757 FOREIGN KEY (id_emplacement_id) REFERENCES emplacement (id)');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT FK_35FE2EFE8458D893 FOREIGN KEY (id_artiste_id) REFERENCES artiste (id)');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT FK_35FE2EFEA43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('CREATE INDEX IDX_35FE2EFE36C5960A ON oeuvre (id_exposition_id)');
        $this->addSql('CREATE INDEX IDX_35FE2EFEF93F3757 ON oeuvre (id_emplacement_id)');
        $this->addSql('CREATE INDEX IDX_35FE2EFE8458D893 ON oeuvre (id_artiste_id)');
        $this->addSql('CREATE INDEX IDX_35FE2EFEA43CD245 ON oeuvre (id_employe_id)');
        $this->addSql('ALTER TABLE traductionoeuvre DROP FOREIGN KEY `traductionoeuvre_ibfk_1`');
        $this->addSql('ALTER TABLE traductionoeuvre DROP FOREIGN KEY `traductionoeuvre_ibfk_2`');
        $this->addSql('ALTER TABLE traductionoeuvre DROP FOREIGN KEY `traductionoeuvre_ibfk_3`');
        $this->addSql('DROP INDEX idEmploye ON traductionoeuvre');
        $this->addSql('DROP INDEX idLangue ON traductionoeuvre');
        $this->addSql('DROP INDEX idxTradOeuvreOeuvreLangue ON traductionoeuvre');
        $this->addSql('DROP INDEX IDX_BA6D1F5356EF8664 ON traductionoeuvre');
        $this->addSql('ALTER TABLE traductionoeuvre MODIFY idTraductionOeuvre INT NOT NULL');
        $this->addSql('ALTER TABLE traductionoeuvre ADD traduction_texte LONGTEXT DEFAULT NULL, ADD date_ajout DATETIME DEFAULT NULL, ADD id_oeuvre_id INT NOT NULL, ADD id_langue_id INT NOT NULL, DROP idOeuvre, DROP idLangue, DROP traductionTexte, DROP dateAjout, CHANGE idTraductionOeuvre id INT AUTO_INCREMENT NOT NULL, CHANGE urlAcces url_acces VARCHAR(500) DEFAULT NULL, CHANGE idEmploye id_employe_id INT DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE traductionoeuvre ADD CONSTRAINT FK_BA6D1F5382CF1CF FOREIGN KEY (id_oeuvre_id) REFERENCES oeuvre (id)');
        $this->addSql('ALTER TABLE traductionoeuvre ADD CONSTRAINT FK_BA6D1F53AA9806EA FOREIGN KEY (id_langue_id) REFERENCES langue (id)');
        $this->addSql('ALTER TABLE traductionoeuvre ADD CONSTRAINT FK_BA6D1F53A43CD245 FOREIGN KEY (id_employe_id) REFERENCES employe (id)');
        $this->addSql('CREATE INDEX IDX_BA6D1F5382CF1CF ON traductionoeuvre (id_oeuvre_id)');
        $this->addSql('CREATE INDEX IDX_BA6D1F53AA9806EA ON traductionoeuvre (id_langue_id)');
        $this->addSql('CREATE INDEX IDX_BA6D1F53A43CD245 ON traductionoeuvre (id_employe_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contenuenrichi (idContenuEnrichi INT AUTO_INCREMENT NOT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, urlAcces VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ordreAffichage INT DEFAULT 1, dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, idOeuvre INT NOT NULL, idEmploye INT DEFAULT NULL, INDEX idEmploye (idEmploye), INDEX idxContenuOeuvre (idOeuvre), INDEX idxContenuOrdre (idOeuvre, ordreAffichage), PRIMARY KEY (idContenuEnrichi)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'Contenus enrichis supplémentaires en français (audio, vidéo, images détail...)\' ');
        $this->addSql('CREATE TABLE traductionartiste (idTraductionArtiste INT AUTO_INCREMENT NOT NULL, idArtiste INT NOT NULL, idLangue INT NOT NULL, traductionTexte TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, urlAcces VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, idEmploye INT DEFAULT NULL, INDEX idEmploye (idEmploye), INDEX idLangue (idLangue), INDEX idxTradArtisteArtisteLangue (idArtiste, idLangue), INDEX IDX_34EF792B8CBE5EBD (idArtiste), PRIMARY KEY (idTraductionArtiste)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'Traductions des descriptions d\'\'artistes\' ');
        $this->addSql('CREATE TABLE traductioncontenuenrichi (idTraductionContenu INT AUTO_INCREMENT NOT NULL, idContenuEnrichi INT NOT NULL, idLangue INT NOT NULL, traductionTexte TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, urlAcces VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ordreAffichage INT DEFAULT 1, dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, idEmploye INT DEFAULT NULL, INDEX idEmploye (idEmploye), INDEX idLangue (idLangue), INDEX idxTradContenuContenuLangue (idContenuEnrichi, idLangue), INDEX idxTradContenuOrdre (idContenuEnrichi, idLangue, ordreAffichage), INDEX IDX_AA4C1CBE2EF5D3A4 (idContenuEnrichi), PRIMARY KEY (idTraductionContenu)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'Traductions des contenus enrichis\' ');
        $this->addSql('CREATE TABLE traductionexpo (idTraductionExpo INT AUTO_INCREMENT NOT NULL, idExposition INT NOT NULL, idLangue INT NOT NULL, traductionTexte TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, urlAcces VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, idEmploye INT DEFAULT NULL, INDEX idEmploye (idEmploye), INDEX idLangue (idLangue), INDEX idxTradExpoExpoLangue (idExposition, idLangue), INDEX IDX_9318632F3EC5E3F9 (idExposition), PRIMARY KEY (idTraductionExpo)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'Traductions des descriptions d\'\'expositions\' ');
        $this->addSql('ALTER TABLE contenuenrichi ADD CONSTRAINT `contenuenrichi_ibfk_1` FOREIGN KEY (idOeuvre) REFERENCES oeuvre (idOeuvre) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contenuenrichi ADD CONSTRAINT `contenuenrichi_ibfk_2` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionartiste ADD CONSTRAINT `traductionartiste_ibfk_1` FOREIGN KEY (idArtiste) REFERENCES artiste (idArtiste) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionartiste ADD CONSTRAINT `traductionartiste_ibfk_2` FOREIGN KEY (idLangue) REFERENCES langue (idLangue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionartiste ADD CONSTRAINT `traductionartiste_ibfk_3` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductioncontenuenrichi ADD CONSTRAINT `traductioncontenuenrichi_ibfk_1` FOREIGN KEY (idContenuEnrichi) REFERENCES contenuenrichi (idContenuEnrichi) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductioncontenuenrichi ADD CONSTRAINT `traductioncontenuenrichi_ibfk_2` FOREIGN KEY (idLangue) REFERENCES langue (idLangue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductioncontenuenrichi ADD CONSTRAINT `traductioncontenuenrichi_ibfk_3` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionexpo ADD CONSTRAINT `traductionexpo_ibfk_1` FOREIGN KEY (idExposition) REFERENCES exposition (idExposition) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionexpo ADD CONSTRAINT `traductionexpo_ibfk_2` FOREIGN KEY (idLangue) REFERENCES langue (idLangue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionexpo ADD CONSTRAINT `traductionexpo_ibfk_3` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contenu_enrichi DROP FOREIGN KEY FK_A88859EA82CF1CF');
        $this->addSql('ALTER TABLE contenu_enrichi DROP FOREIGN KEY FK_A88859EAA43CD245');
        $this->addSql('ALTER TABLE traduction_artiste DROP FOREIGN KEY FK_A238993F8458D893');
        $this->addSql('ALTER TABLE traduction_artiste DROP FOREIGN KEY FK_A238993FAA9806EA');
        $this->addSql('ALTER TABLE traduction_artiste DROP FOREIGN KEY FK_A238993FA43CD245');
        $this->addSql('ALTER TABLE traduction_contenue_enrichie DROP FOREIGN KEY FK_E2C8D358C90CCF4E');
        $this->addSql('ALTER TABLE traduction_contenue_enrichie DROP FOREIGN KEY FK_E2C8D358AA9806EA');
        $this->addSql('ALTER TABLE traduction_contenue_enrichie DROP FOREIGN KEY FK_E2C8D358A43CD245');
        $this->addSql('ALTER TABLE traduction_expo DROP FOREIGN KEY FK_2EE6C63D36C5960A');
        $this->addSql('ALTER TABLE traduction_expo DROP FOREIGN KEY FK_2EE6C63DAA9806EA');
        $this->addSql('ALTER TABLE traduction_expo DROP FOREIGN KEY FK_2EE6C63DA43CD245');
        $this->addSql('DROP TABLE contenu_enrichi');
        $this->addSql('DROP TABLE traduction_artiste');
        $this->addSql('DROP TABLE traduction_contenue_enrichie');
        $this->addSql('DROP TABLE traduction_expo');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE artiste DROP FOREIGN KEY FK_9C07354FA43CD245');
        $this->addSql('DROP INDEX IDX_9C07354FA43CD245 ON artiste');
        $this->addSql('ALTER TABLE artiste MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE artiste ADD anneeNaissance INT DEFAULT NULL, ADD dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, ADD idEmploye INT DEFAULT NULL, DROP annee_naissance, DROP date_ajout, DROP id_employe_id, CHANGE description description TEXT DEFAULT NULL, CHANGE id idArtiste INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idArtiste)');
        $this->addSql('ALTER TABLE artiste ADD CONSTRAINT `artiste_ibfk_1` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX idEmploye ON artiste (idEmploye)');
        $this->addSql('ALTER TABLE configuration MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE configuration CHANGE valeur valeur TEXT DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE id idConfiguration INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idConfiguration)');
        $this->addSql('CREATE UNIQUE INDEX cle ON configuration (cle)');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A682CF1CF');
        $this->addSql('DROP INDEX IDX_964685A682CF1CF ON consultation');
        $this->addSql('ALTER TABLE consultation MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD dateConsultation DATETIME DEFAULT CURRENT_TIMESTAMP, DROP date_consultation, CHANGE id idConsultation INT AUTO_INCREMENT NOT NULL, CHANGE id_oeuvre_id idOeuvre INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idConsultation)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT `consultation_ibfk_1` FOREIGN KEY (idOeuvre) REFERENCES oeuvre (idOeuvre) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX idxConsultationDate ON consultation (dateConsultation)');
        $this->addSql('CREATE INDEX idxConsultationOeuvre ON consultation (idOeuvre)');
        $this->addSql('ALTER TABLE emplacement DROP FOREIGN KEY FK_C0CF65F636BDE04B');
        $this->addSql('ALTER TABLE emplacement DROP FOREIGN KEY FK_C0CF65F636C5960A');
        $this->addSql('DROP INDEX IDX_C0CF65F636BDE04B ON emplacement');
        $this->addSql('DROP INDEX IDX_C0CF65F636C5960A ON emplacement');
        $this->addSql('ALTER TABLE emplacement MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE emplacement ADD positionX NUMERIC(5, 2) DEFAULT NULL, ADD positionY NUMERIC(5, 2) DEFAULT NULL, ADD idEspace INT NOT NULL, ADD idExposition INT NOT NULL, DROP position_x, DROP position_y, DROP id_espace_id, DROP id_exposition_id, CHANGE id idEmplacement INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idEmplacement)');
        $this->addSql('ALTER TABLE emplacement ADD CONSTRAINT `emplacement_ibfk_1` FOREIGN KEY (idEspace) REFERENCES espace (idEspace) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE emplacement ADD CONSTRAINT `emplacement_ibfk_2` FOREIGN KEY (idExposition) REFERENCES exposition (idExposition) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX idxEmplacementEspace ON emplacement (idEspace)');
        $this->addSql('CREATE INDEX idxEmplacementExpo ON emplacement (idExposition)');
        $this->addSql('ALTER TABLE employe DROP FOREIGN KEY FK_F804D3B94F9A54D7');
        $this->addSql('DROP INDEX IDX_F804D3B94F9A54D7 ON employe');
        $this->addSql('ALTER TABLE employe MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE employe ADD dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, ADD dateSuppression DATETIME DEFAULT NULL, ADD idFonction VARCHAR(3) NOT NULL, DROP date_creation, DROP date_suppression, DROP id_fonction_id, CHANGE actif actif TINYINT DEFAULT 1, CHANGE supprime supprime TINYINT DEFAULT 0, CHANGE id idEmploye INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idEmploye)');
        $this->addSql('ALTER TABLE employe ADD CONSTRAINT `employe_ibfk_1` FOREIGN KEY (idFonction) REFERENCES fonction (idFonction) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX email ON employe (email)');
        $this->addSql('CREATE INDEX idFonction ON employe (idFonction)');
        $this->addSql('CREATE INDEX idxEmployeActif ON employe (actif)');
        $this->addSql('CREATE INDEX idxEmployeSupprime ON employe (supprime)');
        $this->addSql('CREATE UNIQUE INDEX login ON employe (login)');
        $this->addSql('ALTER TABLE espace MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE espace CHANGE description description TEXT DEFAULT NULL, CHANGE id idEspace INT AUTO_INCREMENT NOT NULL, CHANGE nom_espace nomEspace VARCHAR(250) NOT NULL, CHANGE superficie_m2 superficieM2 NUMERIC(10, 2) DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idEspace)');
        $this->addSql('CREATE UNIQUE INDEX nomEspace ON espace (nomEspace)');
        $this->addSql('ALTER TABLE etape DROP FOREIGN KEY FK_285F75DD36C5960A');
        $this->addSql('DROP INDEX IDX_285F75DD36C5960A ON etape');
        $this->addSql('ALTER TABLE etape MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE etape CHANGE id idEtape INT AUTO_INCREMENT NOT NULL, CHANGE id_exposition_id idExposition INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idEtape)');
        $this->addSql('ALTER TABLE etape ADD CONSTRAINT `etape_ibfk_1` FOREIGN KEY (idExposition) REFERENCES exposition (idExposition) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX idExposition ON etape (idExposition, ordre)');
        $this->addSql('CREATE INDEX IDX_285F75DD3EC5E3F9 ON etape (idExposition)');
        $this->addSql('ALTER TABLE exposition DROP FOREIGN KEY FK_BC31FD13A43CD245');
        $this->addSql('DROP INDEX IDX_BC31FD13A43CD245 ON exposition');
        $this->addSql('ALTER TABLE exposition MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE exposition ADD dateDebut DATE DEFAULT NULL, ADD dateFin DATE DEFAULT NULL, ADD modulePublicActif TINYINT DEFAULT 0, ADD dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, DROP date_debut, DROP date_fin, DROP module_public_actif, DROP date_creation, CHANGE titre titre VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE theme theme VARCHAR(250) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE horaires horaires TEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description TEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE image image VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE id idExposition INT AUTO_INCREMENT NOT NULL, CHANGE id_employe_id idEmploye INT DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idExposition)');
        $this->addSql('ALTER TABLE exposition ADD CONSTRAINT `exposition_ibfk_1` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX idEmploye ON exposition (idEmploye)');
        $this->addSql('CREATE INDEX idxExpositionActif ON exposition (modulePublicActif)');
        $this->addSql('CREATE INDEX idxExpositionDates ON exposition (dateDebut, dateFin)');
        $this->addSql('ALTER TABLE fonction MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE fonction ADD idFonction VARCHAR(3) NOT NULL, DROP id, CHANGE intitule intitule VARCHAR(250) NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idFonction)');
        $this->addSql('CREATE UNIQUE INDEX intitule ON fonction (intitule)');
        $this->addSql('ALTER TABLE langue MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE langue CHANGE id idLangue INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idLangue)');
        $this->addSql('CREATE UNIQUE INDEX code ON langue (code)');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY FK_35FE2EFE36C5960A');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY FK_35FE2EFEF93F3757');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY FK_35FE2EFE8458D893');
        $this->addSql('ALTER TABLE oeuvre DROP FOREIGN KEY FK_35FE2EFEA43CD245');
        $this->addSql('DROP INDEX IDX_35FE2EFE36C5960A ON oeuvre');
        $this->addSql('DROP INDEX IDX_35FE2EFEF93F3757 ON oeuvre');
        $this->addSql('DROP INDEX IDX_35FE2EFE8458D893 ON oeuvre');
        $this->addSql('DROP INDEX IDX_35FE2EFEA43CD245 ON oeuvre');
        $this->addSql('ALTER TABLE oeuvre MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE oeuvre ADD anneeCreation INT DEFAULT NULL, ADD hauteurCm NUMERIC(10, 2) DEFAULT NULL, ADD largeurCm NUMERIC(10, 2) DEFAULT NULL, ADD profondeurCm NUMERIC(10, 2) DEFAULT NULL, ADD dateLivraisonPrevue DATE DEFAULT NULL, ADD dateLivraisonReelle DATE DEFAULT NULL, ADD numeroIdentification INT DEFAULT NULL, ADD ordreVisite INT DEFAULT NULL, ADD urlQrCode VARCHAR(500) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, ADD idExposition INT DEFAULT NULL, ADD idEmplacement INT DEFAULT NULL, ADD idEmploye INT DEFAULT NULL, DROP annee_creation, DROP hauteur_cm, DROP largeur_cm, DROP profondeur_cm, DROP date_livraison_prevue, DROP date_livraison_reelle, DROP ordre_visite, DROP url_qr_code, DROP datetime, DROP date_ajout, DROP numero_identification, DROP id_exposition_id, DROP id_emplacement_id, DROP id_employe_id, CHANGE titre titre VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description TEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE image image VARCHAR(500) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE technique technique VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE id idOeuvre INT AUTO_INCREMENT NOT NULL, CHANGE id_artiste_id idArtiste INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idOeuvre)');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT `oeuvre_ibfk_1` FOREIGN KEY (idExposition) REFERENCES exposition (idExposition) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT `oeuvre_ibfk_2` FOREIGN KEY (idEmplacement) REFERENCES emplacement (idEmplacement) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT `oeuvre_ibfk_3` FOREIGN KEY (idArtiste) REFERENCES artiste (idArtiste) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE oeuvre ADD CONSTRAINT `oeuvre_ibfk_4` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX idEmplacement ON oeuvre (idEmplacement)');
        $this->addSql('CREATE INDEX idEmploye ON oeuvre (idEmploye)');
        $this->addSql('CREATE INDEX idxOeuvreArtiste ON oeuvre (idArtiste)');
        $this->addSql('CREATE INDEX idxOeuvreExposition ON oeuvre (idExposition)');
        $this->addSql('CREATE INDEX idxOeuvreTechnique ON oeuvre (technique)');
        $this->addSql('CREATE UNIQUE INDEX numeroIdentification ON oeuvre (numeroIdentification)');
        $this->addSql('ALTER TABLE traductionoeuvre DROP FOREIGN KEY FK_BA6D1F5382CF1CF');
        $this->addSql('ALTER TABLE traductionoeuvre DROP FOREIGN KEY FK_BA6D1F53AA9806EA');
        $this->addSql('ALTER TABLE traductionoeuvre DROP FOREIGN KEY FK_BA6D1F53A43CD245');
        $this->addSql('DROP INDEX IDX_BA6D1F5382CF1CF ON traductionoeuvre');
        $this->addSql('DROP INDEX IDX_BA6D1F53AA9806EA ON traductionoeuvre');
        $this->addSql('DROP INDEX IDX_BA6D1F53A43CD245 ON traductionoeuvre');
        $this->addSql('ALTER TABLE traductionoeuvre MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE traductionoeuvre ADD idOeuvre INT NOT NULL, ADD idLangue INT NOT NULL, ADD traductionTexte TEXT DEFAULT NULL, ADD dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, DROP traduction_texte, DROP date_ajout, DROP id_oeuvre_id, DROP id_langue_id, CHANGE id idTraductionOeuvre INT AUTO_INCREMENT NOT NULL, CHANGE url_acces urlAcces VARCHAR(500) DEFAULT NULL, CHANGE id_employe_id idEmploye INT DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idTraductionOeuvre)');
        $this->addSql('ALTER TABLE traductionoeuvre ADD CONSTRAINT `traductionoeuvre_ibfk_1` FOREIGN KEY (idOeuvre) REFERENCES oeuvre (idOeuvre) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionoeuvre ADD CONSTRAINT `traductionoeuvre_ibfk_2` FOREIGN KEY (idLangue) REFERENCES langue (idLangue) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE traductionoeuvre ADD CONSTRAINT `traductionoeuvre_ibfk_3` FOREIGN KEY (idEmploye) REFERENCES employe (idEmploye) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX idEmploye ON traductionoeuvre (idEmploye)');
        $this->addSql('CREATE INDEX idLangue ON traductionoeuvre (idLangue)');
        $this->addSql('CREATE INDEX idxTradOeuvreOeuvreLangue ON traductionoeuvre (idOeuvre, idLangue)');
        $this->addSql('CREATE INDEX IDX_BA6D1F5356EF8664 ON traductionoeuvre (idOeuvre)');
    }
}
